--- 
abstract: Iterate A File By Line
author: 
  - Copyright (c) 2008 Daisuke Maki <daisuke@endeworks.jp>
build_requires: 
  Encode: 0
  utf8: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Iterator-File-Line
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  PerlIO::encoding: 0
  PerlIO::eol: 0
version: 0.00001
